CREATE TABLE "meals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"notion_page_id" text,
	"notion_url" text,
	"household_id" text NOT NULL,
	"created_by" text,
	"visibility" text,
	"schema_version" text,
	"meal_name" text NOT NULL,
	"cuisine" text,
	"meal_type" text,
	"protein_level" text,
	"satiety_level" text,
	"blood_sugar_impact" text,
	"effort_level" text,
	"family_approved" boolean DEFAULT false NOT NULL,
	"weeknight_friendly" boolean DEFAULT false NOT NULL,
	"comfort_meal" boolean DEFAULT false NOT NULL,
	"source_url" text,
	"source_name" text,
	"source_type" text,
	"source_classification" text,
	"source_notes" text,
	"imported_at" timestamp with time zone,
	"last_parsed_at" timestamp with time zone,
	"parser_version" text,
	"analysis_version" text,
	"analysis_model" text,
	"ingredients_text" text,
	"instructions_text" text,
	"optimized_version" text,
	"notes" text,
	"calories" numeric,
	"protein_g" numeric,
	"carbohydrates_g" numeric,
	"fat_g" numeric,
	"fiber_g" numeric,
	"sodium_mg" numeric,
	"sugar_g" numeric,
	"nutrition_confidence" text,
	"nutrition_source" text,
	"nutrition_provenance" text,
	"quality_score" numeric,
	"metabolic_score" numeric,
	"protein_score" numeric,
	"fiber_score" numeric,
	"energy_density_score" numeric,
	"processing_score" numeric,
	"satiety_score_numeric" numeric,
	"blood_sugar_risk_score" numeric,
	"meal_date" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "meals_notion_page_id_unique" UNIQUE("notion_page_id")
);
